### ISSUE TITLE
result = DHT.acquireAndWait(); in example file is wrong.

### ISSUE THREAD

**Issue by htko89** [piettetech/PietteTech_DHT#7]
should be result = DHT.acquireAndWait(0); (or suggested timeout?)
result = DHT.acquireAndWait(); throws an error in particle dev:
no matching function call for 'PietteTech_DHT::acquireAndWait()'

For a newbie at Arduino/C++ code, this confused the crap out of me and took me hours to figure out.

**Comment by mtnscott** [comment]
Sorry about that, I missed the fix.
